# - debug: var=schemata

- name: revert database
  shell: >
    cd ../../db/release/{{ item }} && 
    sqitch revert
    --target "db:pg://{{ db_admin_user_name }}{{ env }}@{{ appservice_name }}-db-{{ env }}:{{ db_admin_user_password }}@{{ appservice_name }}-db-{{ env }}.postgres.database.azure.com/{{ db_name }}"
    --plan-file  sqitch.plan
  loop: "{{ schemata | reverse | list }}"
